force-app/main/default/objects/Product2/fields/Body_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Type__c</fullName>
    <label>Body Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sedan</fullName>
            </value>
            <value>
                <fullName>Coupe</fullName>
            </value>
            <value>
                <fullName>Hatchback 3-door</fullName>
            </value>
            <value>
                <fullName>Hatchback 5-door</fullName>
            </value>
            <value>
                <fullName>Station Wagon</fullName>
            </value>
            <value>
                <fullName>Wagon, SUV</fullName>
            </value>
            <value>
                <fullName>Minivan</fullName>
            </value>
            <value>
                <fullName>Pickup Truck</fullName>
            </value>
            <value>
                <fullName>Coupe,</fullName>
                <isActive>false</isActive>
                <label>Coupe,</label>
            </value>
            <value>
                <fullName>Hatchback 3-door,</fullName>
                <isActive>false</isActive>
                <label>Hatchback 3-door,</label>
            </value>
            <value>
                <fullName>Hatchback 5-door,</fullName>
                <isActive>false</isActive>
                <label>Hatchback 5-door,</label>
            </value>
            <value>
                <fullName>Minivan,</fullName>
                <isActive>false</isActive>
                <label>Minivan,</label>
            </value>
            <value>
                <fullName>SUV,</fullName>
                <isActive>false</isActive>
                <label>SUV,</label>
            </value>
            <value>
                <fullName>Sedan,</fullName>
                <isActive>false</isActive>
                <label>Sedan,</label>
            </value>
            <value>
                <fullName>Station Wagon,</fullName>
                <isActive>false</isActive>
                <label>Station Wagon,</label>
            </value>
            <value>
                <fullName>Wagon,</fullName>
                <isActive>false</isActive>
                <label>Wagon,</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Engine_Capacity_cc_c__c.field-meta.xml
<CustomField>
    <fullName>Engine_Capacity_cc_c__c</fullName>
    <inlineHelpText>api name: Engine_Capacity_cc__c</inlineHelpText>
    <label>Engine Capacity(cc)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Up to 1000</fullName>
            </value>
            <value>
                <fullName>1000 to 1500</fullName>
            </value>
            <value>
                <fullName>1500 to 1800</fullName>
            </value>
            <value>
                <fullName>1800 to 2000</fullName>
            </value>
            <value>
                <fullName>2000 to 2500</fullName>
            </value>
            <value>
                <fullName>Above 2500</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Type__c</fullName>
    <label>Fuel Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gasoline</fullName>
            </value>
            <value>
                <fullName>LPG</fullName>
            </value>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Diesel,</fullName>
                <isActive>false</isActive>
                <label>Diesel,</label>
            </value>
            <value>
                <fullName>Gasoline,</fullName>
                <isActive>false</isActive>
                <label>Gasoline,</label>
            </value>
            <value>
                <fullName>Hybrid,</fullName>
                <isActive>false</isActive>
                <label>Hybrid,</label>
            </value>
            <value>
                <fullName>LPG,</fullName>
                <isActive>false</isActive>
                <label>LPG,</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Gear__c.field-meta.xml
<CustomField>
    <fullName>Gear__c</fullName>
    <label>Gear</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Semi-Automatic</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Manual,</fullName>
                <isActive>false</isActive>
                <label>Manual,</label>
            </value>
            <value>
                <fullName>Semi-Automatic,</fullName>
                <isActive>false</isActive>
                <label>Semi-Automatic,</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/productERPId__c.field-meta.xml
<CustomField>
    <fullName>productERPId__c</fullName>
    <description>This Id come from ERP system.</description>
    <label>productERPId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Wheel_Drive__c.field-meta.xml
<CustomField>
    <fullName>Wheel_Drive__c</fullName>
    <label>Wheel Drive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Front-Wheel Drive</fullName>
            </value>
            <value>
                <fullName>Rear-Wheel Drive</fullName>
            </value>
            <value>
                <fullName>4WD (Continuous)</fullName>
            </value>
            <value>
                <fullName>AWD (Electronic)</fullName>
            </value>
            <value>
                <fullName>4WD (Continuous),</fullName>
                <isActive>false</isActive>
                <label>4WD (Continuous),</label>
            </value>
            <value>
                <fullName>Front-Wheel Drive,</fullName>
                <isActive>false</isActive>
                <label>Front-Wheel Drive,</label>
            </value>
            <value>
                <fullName>Rear-Wheel Drive,</fullName>
                <isActive>false</isActive>
                <label>Rear-Wheel Drive,</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/getProductRecordsFromERP.cls
public class getProductRecordsFromERP {
    @future(Callout=true)
    public static void getProducts(){
        
        HTTP h = new HTTP();
        HTTPRequest request =new HTTPRequest();
        
        request.setMethod('GET');
        request.setEndpoint('https://wisequarter1--erp.sandbox.my.salesforce.com/services/apexrest/ProductWebService');
        request.setHeader('Authorization', 'Bearer 00D780000008gDM!AQcAQDbdbzqIZGm6CPln_q7eHEci7VM2hE64xQGc4OnkFPxcuZydFhpar8RbT9HG_11POGlPDOXnptcmdptTmy2aY_g6HoaZ');
        request.setHeader('Content-Type', 'application/json; charset=utf-8');
        
        HTTPResponse response = h.send(request);
        String jsonBody = response.getBody();
        System.debug('jsonBody>> '+ jsonBody);
        /*jsonBody>> {"prodList":[{"wheelDrive":"Front-Wheel Drive","unitPrice":100.00,"productName":"Test Product1","productERPId":"01t78000000eME6AAM",
        "productCode":"112233","isActive":true,"gear":"Manual","fuelType":"Diesel","engineCapacity":"1000 to 1500","description":"TESTTT","bodyType":"Sedan
        */
       Map<string, Object> jsonBody1 =(Map<String, Object>)JSON.deserializeUntyped(response.getBody());
         System.debug('jsonBody1>>'+jsonBody1);

        /*jsonBody1>>{prodList=({bodyType=Sedan, description=TESTTT, engineCapacity=1000 to 1500, fuelType=Diesel, 
         * gear=Manual, isActive=true, productCode=112233, productERPId=01t78000000eME6AAM, productName=Test Product1, 
         * unitPrice=100.00, ...}, {bodyType=Sedan, description=Honda City is B segment, engineCapacity=1000 to 1500, 
         * fuelType=Gasoline, gear=Manual, isActive=true, productCode=HNCS157965, productERPId=01t78000000eYSoAAM, 
         * productName=Honda City 1.4, unitPrice=2000.00, ...}, {bodyType=Sedan, d
         */
        List<Object> JsonBodyList = (List<Object>)jsonBody1.get('prodList');
        System.debug('JsonBodyList>>'+JsonBodyList);
        /*JsonBodyList>>({bodyType=Sedan, description=TESTTT, engineCapacity=1000 to 1500, fuelType=Diesel, 
         * gear=Manual, isActive=true, productCode=112233, productERPId=01t78000000eME6AAM, productName=Test Product1,
         *  unitPrice=100.00, ...}, {bodyType=Sedan, description=Honda City is B segment, engineCapacity=1000 to 1500,
         *  fuelType=Gasoline, gear=Manual, isActive=true, productCode=HNCS157965, productERPId=01t78000000eYSoAAM,
         *  productName=Honda City 1.4, unitPrice=2000.00, ...}, {bodyType=Sedan, descript
         */
 
        List<Product2> productList =new List<product2>();
        for(Object o: JsonBodyList){
            Map<String,Object> mapobj = (Map<String,Object>)o;
            System.debug('mapobj>> '+ mapobj);
            Product2 product = new Product2();
            product.Wheel_Drive__c = (String)mapobj.get('wheelDrive');
            product.Name = (String)mapobj.get('productName');
            product.productERPId__c= (String)mapobj.get('productERPId');
            product.ProductCode= (String)mapobj.get('productCode');
            product.IsActive= true;
            product.Gear__c= (String)mapobj.get('gear');
            product.Fuel_Type__c= (String)mapobj.get('fuelType');
            product.Engine_Capacity_cc_c__c= (String)mapobj.get('engineCapacity');
            product.Description= (String)mapobj.get('description');
            product.Body_Type__c= (String)mapobj.get('bodyType');
            
			productList.add(product);       
        }
        	Database.insert(productList);
    }

}